CREATE TABLE `Process`(`ProcessID` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
                       `DepartmentChairman` int(3),
                       `AccountsController` int(3),
                       `CollegeInspector` int(3),
                       `Librarian` int(3),
                       `ExamController` int(3),
                       `ChiefEngineer` int(3),
                       `ChiefMedicalOfficer` int(3),
                       `DirectorDPD` int(3),
                       `DRTeacherCellRO` int(3),
                       `DRAcademicCellRO` int(3),
                       `DRHomeLoanBranchRO` int(3),
                       `DRConfidentialBranchRO` int(3),
                       `DRHigherStudyBranchRO` int(3),
                      ); 
                       